insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Community Outreach Specialist', 32, 'Davie', 'Skey', 16, 1);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Information Systems Manager', 39, 'Thain', 'Suller', 74, 2);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Occupational Therapist', 18, 'Sylvester', 'Grant', 35, 3);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Actuary', 20, 'Somerset', 'Fearnyhough', 67, 4);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Registered Nurse', 22, 'Rhett', 'Kalberer', 64, 5);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Internal Auditor', 30, 'Zandra', 'Dalziel', 33, 6);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Actuary', 21, 'Sanson', 'Dowber', 100, 7);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Food Chemist', 35, 'Viole', 'Gretton', 17, 8);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Teacher', 40, 'Rozella', 'Fife', 22, 9);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Associate Professor', 24, 'Minna', 'Carabet', 47, 10);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Research Nurse', 22, 'Veronique', 'Londesborough', 20, 11);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Database Administrator I', 29, 'Rosco', 'Frensch', 59, 12);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Tax Accountant', 25, 'Erinna', 'Haughey', 72, 13);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Software Test Engineer IV', 19, 'Sydel', 'Tull', 68, 14);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Automation Specialist II', 29, 'Otho', 'Widdocks', 14, 15);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Compensation Analyst', 22, 'Ines', 'McGiven', 35, 16);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Account Coordinator', 24, 'Rollie', 'Kaman', 86, 17);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Marketing Assistant', 21, 'Diane-marie', 'Pauler', 41, 18);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Accountant IV', 38, 'Chevalier', 'Jirak', 11, 19);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Internal Auditor', 21, 'Ignatius', 'Skellon', 54, 20);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Director of Sales', 17, 'Dennie', 'Kain', 95, 21);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Speech Pathologist', 29, 'Deeyn', 'Izac', 94, 22);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Nurse', 31, 'Huntington', 'Rucklidge', 54, 23);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Desktop Support Technician', 18, 'Agnes', 'Friary', 93, 24);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Safety Technician I', 19, 'Wilburt', 'Bolden', 78, 25);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Desktop Support Technician', 38, 'Bren', 'Ceaplen', 42, 26);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Help Desk Technician', 39, 'Lana', 'Bernadon', 52, 27);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Research Nurse', 16, 'Tracey', 'Foldes', 16, 28);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Staff Scientist', 16, 'Starla', 'Toyne', 40, 29);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Technical Writer', 17, 'Erin', 'Arter', 100, 30);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Information Systems Manager', 34, 'Simona', 'Lorkings', 54, 31);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Marketing Manager', 31, 'Madlin', 'Stanners', 46, 32);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Tax Accountant', 25, 'Ninetta', 'McGifford', 26, 33);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Administrative Assistant III', 17, 'Cherri', 'Vere', 80, 34);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Software Consultant', 20, 'Germain', 'Caseley', 3, 35);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Assistant Media Planner', 23, 'Paco', 'McLurg', 61, 36);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Programmer Analyst II', 38, 'Thorstein', 'Bixley', 22, 37);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('General Manager', 22, 'Maddy', 'Huton', 67, 38);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Tax Accountant', 27, 'Alric', 'Lynde', 60, 39);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Information Systems Manager', 21, 'Jens', 'Thompson', 38, 40);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Human Resources Assistant I', 15, 'Pippy', 'Blackstone', 3, 41);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Automation Specialist III', 32, 'Barry', 'Tunnacliffe', 3, 42);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Account Coordinator', 15, 'Ursuline', 'Brunone', 88, 43);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Nurse Practicioner', 19, 'Lilla', 'Inchan', 46, 44);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Operator', 20, 'Brietta', 'Ladell', 91, 45);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Assistant Professor', 40, 'Yettie', 'Haps', 58, 46);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Media Manager I', 24, 'Morgun', 'Grisedale', 19, 47);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Associate Professor', 16, 'Molli', 'Hemmingway', 77, 48);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Structural Analysis Engineer', 39, 'Anitra', 'Inglefield', 62, 49);
insert into Users (role, hourlyRate, firstName, lastName, sharesOwned, id) values ('Information Systems Manager', 29, 'Johnna', 'Dehm', 96, 50);
