USE Scheduling;
DELETE FROM Users WHERE True;

INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Community Outreach Specialist', 32, 'Davie', 'Skey', 16, 1);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Information Systems Manager', 39, 'Thain', 'Suller', 74, 2);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Occupational Therapist', 18, 'Sylvester', 'Grant', 35, 3);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Actuary', 20, 'Somerset', 'Fearnyhough', 67, 4);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Registered Nurse', 22, 'Rhett', 'Kalberer', 64, 5);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Internal Auditor', 30, 'Zandra', 'Dalziel', 33, 6);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Actuary', 21, 'Sanson', 'Dowber', 100, 7);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Food Chemist', 35, 'Viole', 'Gretton', 17, 8);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Teacher', 40, 'Rozella', 'Fife', 22, 9);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Associate Professor', 24, 'Minna', 'Carabet', 47, 10);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Research Nurse', 22, 'Veronique', 'Londesborough', 20, 11);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Database Administrator I', 29, 'Rosco', 'Frensch', 59, 12);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Tax Accountant', 25, 'Erinna', 'Haughey', 72, 13);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Software Test Engineer IV', 19, 'Sydel', 'Tull', 68, 14);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Automation Specialist II', 29, 'Otho', 'Widdocks', 14, 15);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Compensation Analyst', 22, 'Ines', 'McGiven', 35, 16);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Account Coordinator', 24, 'Rollie', 'Kaman', 86, 17);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Marketing Assistant', 21, 'Diane-marie', 'Pauler', 41, 18);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Accountant IV', 38, 'Chevalier', 'Jirak', 11, 19);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Internal Auditor', 21, 'Ignatius', 'Skellon', 54, 20);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Director of Sales', 17, 'Dennie', 'Kain', 95, 21);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Speech Pathologist', 29, 'Deeyn', 'Izac', 94, 22);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Nurse', 31, 'Huntington', 'Rucklidge', 54, 23);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Desktop Support Technician', 18, 'Agnes', 'Friary', 93, 24);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Safety Technician I', 19, 'Wilburt', 'Bolden', 78, 25);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Desktop Support Technician', 38, 'Bren', 'Ceaplen', 42, 26);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Help Desk Technician', 39, 'Lana', 'Bernadon', 52, 27);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Research Nurse', 16, 'Tracey', 'Foldes', 16, 28);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Staff Scientist', 16, 'Starla', 'Toyne', 40, 29);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Technical Writer', 17, 'Erin', 'Arter', 100, 30);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Information Systems Manager', 34, 'Simona', 'Lorkings', 54, 31);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Marketing Manager', 31, 'Madlin', 'Stanners', 46, 32);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Tax Accountant', 25, 'Ninetta', 'McGifford', 26, 33);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Administrative Assistant III', 17, 'Cherri', 'Vere', 80, 34);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Software Consultant', 20, 'Germain', 'Caseley', 3, 35);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Assistant Media Planner', 23, 'Paco', 'McLurg', 61, 36);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Programmer Analyst II', 38, 'Thorstein', 'Bixley', 22, 37);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('General Manager', 22, 'Maddy', 'Huton', 67, 38);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Tax Accountant', 27, 'Alric', 'Lynde', 60, 39);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Information Systems Manager', 21, 'Jens', 'Thompson', 38, 40);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Human Resources Assistant I', 15, 'Pippy', 'Blackstone', 3, 41);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Automation Specialist III', 32, 'Barry', 'Tunnacliffe', 3, 42);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Account Coordinator', 15, 'Ursuline', 'Brunone', 88, 43);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Nurse Practicioner', 19, 'Lilla', 'Inchan', 46, 44);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Operator', 20, 'Brietta', 'Ladell', 91, 45);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Assistant Professor', 40, 'Yettie', 'Haps', 58, 46);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Media Manager I', 24, 'Morgun', 'Grisedale', 19, 47);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Associate Professor', 16, 'Molli', 'Hemmingway', 77, 48);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Structural Analysis Engineer', 39, 'Anitra', 'Inglefield', 62, 49);
INSERT INTO Users (role, hourlyRate, firstName, lastName, sharesOwned, id) VALUES ('Information Systems Manager', 29, 'Johnna', 'Dehm', 96, 50);
