insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Desktop Support Technician', 7, '11:49 PM', '7:46 PM', 0, 38, 30, 1);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('General Manager', 3, '5:47 AM', '12:54 AM', 1, 12, 36, 2);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Technical Writer', 5, '5:32 PM', '7:00 AM', 1, 47, 39, 3);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Chief Design Engineer', 3, '9:24 AM', '4:20 PM', 1, 20, 2, 4);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Accounting', 1, '1:23 AM', '11:50 PM', 0, 10, 42, 5);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Professor', 2, '12:02 PM', '5:29 AM', 1, 23, 1, 6);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Tax Accountant', 7, '9:19 AM', '1:21 PM', 0, 45, 46, 7);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Research Nurse', 2, '10:37 PM', '6:32 PM', 0, 23, 48, 8);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Financial Analyst', 1, '9:24 PM', '4:23 PM', 0, 35, 50, 9);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Account Coordinator', 5, '7:24 AM', '3:28 PM', 0, 22, 5, 10);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Financial Analyst', 2, '4:03 PM', '12:52 PM', 1, 18, 20, 11);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Food Chemist', 6, '4:41 AM', '10:11 PM', 1, 35, 5, 12);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Media Manager III', 4, '11:42 AM', '4:28 AM', 1, 26, 12, 13);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Systems Administrator I', 5, '12:06 AM', '2:50 AM', 0, 36, 18, 14);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Marketing', 6, '8:34 PM', '3:19 AM', 1, 1, 22, 15);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Safety Technician III', 4, '4:35 AM', '11:56 PM', 0, 12, 19, 16);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Recruiter', 7, '7:39 PM', '9:09 PM', 0, 45, 33, 17);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Community Outreach Specialist', 7, '7:25 PM', '9:07 PM', 1, 16, 47, 18);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Software Consultant', 5, '5:40 PM', '3:42 PM', 1, 18, 11, 19);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Speech Pathologist', 4, '4:57 PM', '4:04 AM', 0, 3, 18, 20);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Electrical Engineer', 1, '1:47 PM', '12:57 AM', 0, 18, 21, 21);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Speech Pathologist', 4, '6:42 PM', '12:21 PM', 0, 42, 7, 22);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Recruiter', 6, '12:53 AM', '4:21 AM', 1, 28, 21, 23);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Professor', 6, '6:32 PM', '11:05 PM', 0, 19, 48, 24);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Assistant Manager', 2, '7:47 AM', '10:26 AM', 0, 29, 35, 25);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Junior Executive', 3, '7:28 PM', '12:33 PM', 0, 11, 48, 26);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Analog Circuit Design manager', 5, '2:26 AM', '5:45 AM', 1, 25, 13, 27);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Human Resources Assistant III', 7, '6:41 PM', '6:15 PM', 1, 26, 27, 28);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Desktop Support Technician', 6, '3:14 PM', '7:53 AM', 0, 43, 48, 29);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('GIS Technical Architect', 4, '7:39 PM', '9:10 PM', 1, 12, 27, 30);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Software Test Engineer II', 7, '7:53 PM', '4:58 AM', 1, 43, 19, 31);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Engineer III', 7, '8:44 PM', '7:44 PM', 0, 20, 14, 32);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('GIS Technical Architect', 6, '2:53 PM', '1:22 AM', 0, 17, 44, 33);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Budget/Accounting Analyst I', 1, '5:54 AM', '7:05 AM', 1, 50, 39, 34);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Cost Accountant', 3, '12:08 PM', '7:07 PM', 1, 46, 23, 35);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Tax Accountant', 3, '7:53 AM', '12:28 PM', 1, 8, 15, 36);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Technical Writer', 7, '11:56 AM', '9:43 AM', 0, 29, 9, 37);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Accounting', 6, '2:25 PM', '3:29 PM', 1, 30, 41, 38);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Biostatistician I', 5, '11:39 AM', '1:03 AM', 0, 41, 3, 39);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Editor', 5, '3:19 AM', '9:17 AM', 0, 26, 30, 40);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Business Systems Development Analyst', 1, '4:17 AM', '6:34 AM', 0, 39, 34, 41);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Director of Sales', 6, '8:07 AM', '7:44 PM', 0, 12, 32, 42);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Media Manager III', 1, '9:14 PM', '3:45 PM', 1, 6, 20, 43);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Project Manager', 3, '2:19 PM', '6:17 AM', 1, 30, 46, 44);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Electrical Engineer', 2, '10:59 PM', '2:13 AM', 0, 7, 37, 45);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Food Chemist', 7, '11:10 AM', '8:12 AM', 1, 1, 44, 46);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Analyst Programmer', 1, '9:08 PM', '3:01 AM', 1, 28, 27, 47);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Geologist II', 7, '9:02 AM', '6:08 AM', 0, 39, 7, 48);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('GIS Technical Architect', 1, '2:08 AM', '1:45 AM', 0, 5, 26, 49);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Food Chemist', 7, '10:53 AM', '7:10 AM', 0, 25, 39, 50);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Electrical Engineer', 7, '3:31 PM', '1:05 PM', 1, 41, 10, 51);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Financial Analyst', 2, '7:07 PM', '5:30 AM', 1, 11, 31, 52);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Clinical Specialist', 1, '5:06 PM', '1:20 PM', 1, 47, 3, 53);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Software Test Engineer II', 7, '8:09 AM', '8:14 AM', 1, 5, 48, 54);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Administrative Officer', 6, '3:40 AM', '6:45 PM', 0, 11, 31, 55);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Structural Analysis Engineer', 4, '12:21 AM', '5:07 AM', 0, 20, 38, 56);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Tax Accountant', 3, '11:48 AM', '7:39 PM', 1, 49, 17, 57);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Automation Specialist I', 3, '9:30 AM', '6:41 PM', 1, 40, 31, 58);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Geologist IV', 5, '11:30 PM', '2:08 PM', 0, 8, 44, 59);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('General Manager', 5, '1:56 AM', '2:06 AM', 1, 26, 35, 60);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Actuary', 6, '12:45 AM', '7:32 AM', 1, 15, 35, 61);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Product Engineer', 4, '9:43 AM', '11:48 AM', 0, 39, 39, 62);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Web Developer I', 7, '9:41 PM', '11:54 PM', 1, 23, 30, 63);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Accounting', 6, '7:17 AM', '9:08 AM', 1, 1, 19, 64);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Executive Secretary', 5, '2:32 AM', '9:57 AM', 0, 1, 47, 65);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Environmental Specialist', 5, '5:01 PM', '11:33 AM', 1, 39, 35, 66);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Research Associate', 5, '2:34 PM', '5:30 AM', 0, 39, 1, 67);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Design Engineer', 2, '4:11 AM', '4:39 AM', 0, 50, 43, 68);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Account Executive', 7, '3:58 PM', '5:19 PM', 1, 47, 47, 69);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Design Engineer', 6, '11:06 AM', '7:04 PM', 0, 12, 1, 70);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Chief Design Engineer', 4, '6:20 AM', '4:42 AM', 0, 42, 14, 71);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Accounting Assistant IV', 4, '1:36 PM', '8:04 AM', 1, 22, 24, 72);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Administrative Officer', 2, '8:56 PM', '12:50 AM', 0, 1, 22, 73);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Operator', 4, '4:00 PM', '6:56 PM', 1, 2, 50, 74);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Director of Sales', 5, '1:50 PM', '2:56 AM', 0, 14, 38, 75);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Desktop Support Technician', 7, '2:01 PM', '2:45 AM', 0, 16, 30, 76);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Compensation Analyst', 2, '1:54 PM', '5:08 AM', 1, 26, 20, 77);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Accounting', 6, '8:16 PM', '4:47 PM', 1, 27, 35, 78);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Human Resources Assistant III', 2, '8:07 PM', '7:30 AM', 1, 48, 41, 79);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Marketing Assistant', 4, '9:46 PM', '6:45 PM', 1, 35, 36, 80);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Web Developer III', 3, '4:54 PM', '10:40 AM', 1, 45, 39, 81);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Civil Engineer', 6, '11:57 AM', '10:08 PM', 1, 28, 40, 82);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Legal Assistant', 4, '11:00 PM', '10:54 AM', 1, 9, 11, 83);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Design Engineer', 3, '7:13 PM', '7:53 AM', 1, 18, 47, 84);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Social Worker', 4, '5:50 PM', '6:06 PM', 1, 45, 42, 85);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Operator', 2, '9:05 PM', '1:43 AM', 1, 28, 25, 86);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Registered Nurse', 4, '9:52 PM', '8:09 PM', 0, 19, 35, 87);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Occupational Therapist', 7, '1:41 PM', '1:58 PM', 0, 34, 17, 88);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Automation Specialist II', 6, '1:36 AM', '5:25 AM', 0, 44, 1, 89);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Information Systems Manager', 1, '3:23 AM', '3:29 PM', 1, 21, 45, 90);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Budget/Accounting Analyst IV', 4, '7:11 AM', '7:19 PM', 1, 19, 22, 91);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Legal Assistant', 6, '2:32 PM', '7:18 AM', 1, 5, 45, 92);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Tax Accountant', 6, '4:34 AM', '5:56 PM', 0, 14, 20, 93);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Database Administrator III', 3, '2:51 AM', '10:05 AM', 0, 8, 18, 94);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Accountant IV', 3, '3:50 PM', '12:29 AM', 0, 15, 13, 95);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Programmer Analyst IV', 7, '4:05 PM', '1:15 PM', 0, 34, 16, 96);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Quality Control', 6, '6:45 PM', '7:25 PM', 1, 42, 47, 97);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Financial Analyst', 4, '10:05 AM', '6:30 AM', 1, 50, 31, 98);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Assistant Professor', 4, '12:59 AM', '7:55 PM', 1, 33, 34, 99);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Automation Specialist I', 5, '8:59 AM', '8:50 AM', 0, 28, 18, 100);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Recruiter', 3, '5:31 AM', '1:14 PM', 1, 34, 33, 101);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('GIS Technical Architect', 1, '11:20 AM', '1:30 AM', 0, 28, 15, 102);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Human Resources Assistant IV', 2, '11:28 PM', '3:19 AM', 0, 24, 17, 103);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Civil Engineer', 4, '7:08 PM', '12:59 AM', 0, 47, 11, 104);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Payment Adjustment Coordinator', 7, '12:05 AM', '8:15 PM', 1, 35, 46, 105);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Assistant Media Planner', 3, '5:38 AM', '7:53 AM', 1, 26, 25, 106);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Software Consultant', 4, '4:16 AM', '9:25 AM', 0, 39, 21, 107);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Tax Accountant', 2, '3:34 PM', '10:12 AM', 0, 18, 29, 108);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Administrative Officer', 2, '7:19 AM', '12:03 PM', 0, 10, 31, 109);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Sales Associate', 3, '2:30 AM', '3:53 AM', 0, 21, 27, 110);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Analog Circuit Design manager', 3, '10:09 PM', '1:06 AM', 1, 19, 13, 111);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Associate Professor', 3, '8:48 PM', '4:52 AM', 1, 20, 47, 112);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Engineer II', 3, '7:03 AM', '11:24 PM', 1, 3, 43, 113);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Automation Specialist II', 3, '1:08 AM', '10:10 PM', 1, 8, 12, 114);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Professor', 3, '6:58 AM', '5:53 AM', 0, 19, 23, 115);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Budget/Accounting Analyst I', 6, '4:19 PM', '10:45 PM', 0, 31, 28, 116);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Marketing', 5, '7:34 AM', '10:14 AM', 0, 38, 46, 117);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Web Designer III', 5, '9:49 AM', '7:53 PM', 0, 41, 2, 118);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Account Executive', 3, '11:40 PM', '2:28 AM', 1, 23, 19, 119);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Nurse Practicioner', 5, '3:27 AM', '10:43 AM', 1, 34, 29, 120);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Junior Executive', 3, '5:19 AM', '12:33 PM', 0, 46, 46, 121);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Compensation Analyst', 2, '6:23 PM', '9:19 PM', 1, 4, 21, 122);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Social Worker', 5, '2:56 PM', '3:13 AM', 1, 21, 9, 123);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Clinical Specialist', 1, '2:27 PM', '12:09 AM', 0, 34, 19, 124);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Mechanical Systems Engineer', 5, '1:39 PM', '6:31 AM', 1, 50, 1, 125);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Statistician I', 3, '1:30 AM', '9:45 PM', 1, 26, 7, 126);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Editor', 1, '2:17 PM', '7:11 AM', 1, 26, 11, 127);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Professor', 3, '9:30 PM', '4:32 AM', 0, 3, 31, 128);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Research Associate', 7, '5:30 PM', '8:15 AM', 0, 35, 23, 129);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Electrical Engineer', 7, '12:50 AM', '10:23 AM', 0, 47, 37, 130);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Paralegal', 1, '9:50 PM', '8:48 AM', 1, 10, 18, 131);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Quality Engineer', 7, '10:26 PM', '1:26 PM', 1, 40, 12, 132);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Geological Engineer', 6, '7:18 AM', '1:14 AM', 0, 22, 40, 133);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Teacher', 4, '4:36 AM', '4:28 AM', 1, 50, 12, 134);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Web Designer III', 2, '9:55 AM', '3:14 AM', 0, 42, 14, 135);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Help Desk Technician', 5, '2:15 PM', '1:30 AM', 1, 28, 19, 136);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Staff Scientist', 3, '1:20 AM', '6:14 PM', 0, 9, 30, 137);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Safety Technician I', 3, '12:48 PM', '7:09 PM', 1, 3, 50, 138);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Quality Control Specialist', 7, '6:22 PM', '9:15 AM', 0, 2, 36, 139);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Financial Analyst', 4, '3:30 PM', '9:06 PM', 0, 16, 27, 140);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('VP Product Management', 7, '11:38 AM', '8:54 AM', 1, 50, 26, 141);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Assistant Media Planner', 4, '11:11 AM', '3:34 PM', 1, 29, 8, 142);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Editor', 1, '12:37 AM', '10:51 AM', 1, 24, 38, 143);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Sales Associate', 5, '2:51 PM', '7:07 AM', 0, 1, 42, 144);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Paralegal', 6, '5:47 PM', '8:48 PM', 0, 6, 6, 145);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Human Resources Assistant III', 4, '2:58 AM', '10:23 AM', 0, 33, 22, 146);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Graphic Designer', 1, '6:06 AM', '4:36 AM', 1, 27, 27, 147);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Administrative Assistant III', 6, '9:56 AM', '10:37 PM', 1, 40, 25, 148);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Pharmacist', 2, '4:27 PM', '5:25 PM', 0, 31, 43, 149);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Research Nurse', 6, '12:56 PM', '7:26 AM', 1, 10, 33, 150);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Cost Accountant', 3, '4:59 AM', '10:18 PM', 0, 44, 12, 151);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('General Manager', 2, '10:59 AM', '9:22 PM', 0, 12, 4, 152);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Research Assistant III', 4, '9:38 PM', '10:59 AM', 0, 3, 18, 153);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Pharmacist', 6, '2:47 AM', '12:33 AM', 0, 20, 23, 154);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Electrical Engineer', 5, '9:28 PM', '8:33 AM', 0, 40, 28, 155);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Physical Therapy Assistant', 1, '6:18 AM', '11:13 AM', 0, 37, 1, 156);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Geologist I', 7, '12:12 AM', '9:47 PM', 0, 14, 9, 157);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Environmental Tech', 1, '2:07 AM', '9:46 PM', 0, 13, 5, 158);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Pharmacist', 6, '5:53 PM', '1:28 AM', 1, 4, 4, 159);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Recruiting Manager', 4, '3:23 PM', '5:39 PM', 1, 45, 10, 160);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Programmer I', 3, '11:33 AM', '2:20 AM', 1, 18, 26, 161);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('GIS Technical Architect', 7, '6:15 PM', '1:29 PM', 1, 44, 42, 162);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Product Engineer', 2, '5:00 PM', '3:45 AM', 0, 19, 12, 163);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Statistician IV', 2, '9:48 PM', '6:52 PM', 0, 10, 33, 164);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Junior Executive', 5, '5:17 AM', '6:13 AM', 0, 35, 9, 165);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Nurse', 1, '10:33 PM', '3:11 PM', 0, 30, 29, 166);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Help Desk Operator', 1, '1:59 AM', '4:54 PM', 1, 33, 11, 167);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Programmer Analyst IV', 7, '10:25 PM', '5:25 PM', 0, 2, 16, 168);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Administrative Officer', 3, '9:16 PM', '4:26 PM', 0, 3, 13, 169);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Administrative Assistant I', 1, '3:07 AM', '5:36 AM', 0, 7, 4, 170);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Research Assistant IV', 7, '4:45 AM', '9:02 PM', 0, 12, 21, 171);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Programmer II', 1, '12:23 PM', '4:23 PM', 1, 18, 12, 172);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Account Coordinator', 2, '6:31 AM', '3:13 AM', 1, 43, 33, 173);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Environmental Specialist', 2, '6:38 AM', '12:59 PM', 1, 10, 31, 174);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Editor', 4, '6:28 AM', '5:10 AM', 1, 15, 27, 175);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Web Designer III', 2, '4:35 AM', '5:28 AM', 0, 25, 26, 176);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Graphic Designer', 5, '10:42 PM', '9:41 PM', 0, 7, 12, 177);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Marketing Manager', 7, '9:26 PM', '9:37 PM', 1, 33, 2, 178);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Technical Writer', 2, '2:54 PM', '10:57 AM', 0, 40, 22, 179);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Internal Auditor', 5, '8:50 AM', '5:35 AM', 1, 7, 21, 180);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Technical Writer', 3, '11:46 AM', '11:05 PM', 0, 33, 45, 181);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Health Coach I', 3, '7:29 AM', '12:13 PM', 1, 8, 49, 182);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Design Engineer', 6, '7:11 AM', '4:38 PM', 0, 41, 30, 183);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Editor', 4, '7:37 AM', '3:22 AM', 0, 34, 49, 184);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Quality Engineer', 2, '10:26 AM', '10:01 PM', 1, 27, 5, 185);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Marketing Manager', 2, '3:36 PM', '6:22 PM', 1, 50, 26, 186);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Operator', 2, '6:15 PM', '3:14 PM', 0, 29, 14, 187);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Occupational Therapist', 7, '3:49 PM', '2:43 AM', 0, 24, 9, 188);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Senior Sales Associate', 4, '4:13 AM', '11:28 PM', 0, 15, 40, 189);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Systems Administrator IV', 3, '2:38 PM', '12:38 PM', 1, 8, 34, 190);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Human Resources Assistant IV', 3, '9:40 AM', '10:39 PM', 0, 6, 49, 191);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Professor', 3, '3:38 AM', '2:34 PM', 0, 5, 21, 192);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Human Resources Manager', 3, '8:54 AM', '6:17 PM', 1, 13, 3, 193);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Occupational Therapist', 3, '4:45 AM', '7:32 PM', 0, 44, 30, 194);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Geological Engineer', 4, '11:35 PM', '3:13 PM', 0, 40, 24, 195);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Legal Assistant', 5, '8:26 AM', '11:27 AM', 0, 31, 13, 196);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Food Chemist', 5, '6:30 AM', '7:54 PM', 1, 9, 43, 197);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Physical Therapy Assistant', 4, '10:13 PM', '1:47 AM', 0, 7, 47, 198);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Environmental Specialist', 6, '5:02 PM', '6:03 PM', 0, 24, 40, 199);
insert into Shifts (duty, dayOfWeek, startTime, endTime, overtime, employee, schedule, id) values ('Accounting Assistant III', 6, '8:41 AM', '2:04 PM', 1, 31, 9, 200);
